# Network Partition Failover Test Scenario
# This scenario tests failover when a network partition occurs between datacenters

test_id: "network_partition_001"
description: "Test cross-DC failover when network partition occurs between primary and secondary DCs"

# Streams application bundle to test
streams_application_sab: "applications/crossdc_sample_app.sab"

# Parameters for application submission
submission_params:
  jobName: "CrossDCFailoverTest"
  crossDCFailoverEnabled: "true"
  primaryDataCenter: "dc1"
  secondaryDataCenter: "dc2"
  heartbeatIntervalSeconds: "5"
  failoverTimeoutSeconds: "30"

# Pre-failover data injection configuration
pre_failover_data:
  generator_type: "deterministic"
  event_count: 10000
  data_format: "json"
  injection_rate_events_per_second: 100
  batch_size: 500
  schema:
    event_id: "string"
    timestamp: "timestamp"
    value: "number"
    payload: "string"

# Fault scenario configuration
fault_scenario:
  type: "network_partition"
  host: "primary-host"
  target_network: "10.0.2.0/24"  # Secondary DC network
  duration_seconds: 300  # How long to maintain the partition

# The expected failover condition
failover_condition: "automatic"  # The toolkit should detect and trigger failover automatically

# Validation checks after failover
post_failover_validation_checks:
  - type: "data_integrity"
    description: "Verify that all data was processed correctly"
  - type: "performance"
    description: "Verify that processing throughput recovered"
    threshold: 90.0  # Should recover to at least 90% of pre-failure throughput
    metric: "tuples_per_second"
  - type: "availability"
    description: "Verify that application is available in secondary DC"

# Recovery time objective (RTO) - how long should failover take
expected_recovery_time_seconds: 60

# Recovery point objective (RPO) - how much data loss is acceptable
expected_data_loss_percentage: 1.0  # Up to 1% data loss is acceptable

# Expected metrics after failover
expected_metrics:
  health_percentage:
    min: 95.0
    description: "Overall application health percentage"
  error_rate:
    max: 0.5
    description: "Error rate percentage should be low"
  cpu_utilization:
    max: 80.0
    description: "CPU utilization percentage"